name: Analyze Backstage Integration Candidates

on:
  schedule:
    - cron: '0 0 * * MON'  # Run weekly on Monday at midnight
  workflow_dispatch:
    inputs:
      organization:
        description: 'GitHub Organization Name'
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
          GITHUB_ORG: ${{ github.event.inputs.organization || secrets.DEFAULT_ORG }}
          GITHUB_API_URL: ${{ secrets.GITHUB_API_URL }}
        run: |
          python - <<EOF
          from backstage_automation import BackstageAutomation
          import os
          
          automation = BackstageAutomation(
              os.environ["GITHUB_TOKEN"],
              os.environ["GITHUB_ORG"],
              os.environ.get("GITHUB_API_URL")
          )
          
          # Generate and save priority report
          report = automation.generate_priority_report()
          with open("priority_report.md", "w") as f:
              f.write(report)
          EOF

      - name: Create GitHub Issue with Report
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.AUTOMATION_TOKEN }}
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('priority_report.md', 'utf8');
            
            const today = new Date().toISOString().split('T')[0];
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.name,
              title: `Backstage Integration Candidates Report - ${today}`,
              body: report,
              labels: ['backstage-automation', 'priority-report']
            });

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backstage-priority-report
          path: priority_report.md
